name: cv-demo-ui
image: ${artifact.metadata.image}
replicas: 1

env:
  config:
    STABLE_ENDPOINT: ${serviceVariable.stableEndpoint}
    CANARY_ENDPOINT: ${serviceVariable.canaryEndpoint}
    LOG_CONFIG_LABELS: |-
      {
        logsPerMinute: "Logs per minute",
        errorRate: "Error rate (%)",
        errorMessage: "Error message"
      }
    METRIC_CONFIG_LABELS: |-
      {
        callsPerMinute: "Calls per minute",
        errorRate: "Error rate (%)",
        minErrorValue: "Error value min",
        maxErrorValue: "Error value max",
        shouldDoDelayedCalls: "Delayed calls enabled"
      }