apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
spec:
  {{- if .Values.loadBalancerIP}}
  loadBalancerIP: {{.Values.loadBalancerIP}}
  {{- end}}
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 9090
  selector:
    app: prometheus-server
  type: LoadBalancer
