harnessApiVersion: '1.0'
type: PROMETHEUS
alertEnabled: false
alertThreshold: 0.5
analysisTolerance: LOW
connectorName: Prometheus-cv-demo
enabled24x7: true
serviceName: cv-demo
timeSeriesList:
- metricName: error_call
  metricType: ERROR
  txnName: custom
  url: io_harness_custom_metric_error_call{app="cv-demo"}
- metricName: normal_call
  metricType: THROUGHPUT
  txnName: custom
  url: io_harness_custom_metric_normal_call{app="cv-demo"}
