apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Values.name}}
  labels:
    app: {{.Values.name}}
data:
{{.Values.env.config | toYaml | indent 2}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.name}}
spec:
  replicas: {{int .Values.replicas}}
  selector:
    matchLabels:
      app: {{.Values.name}}
  template:
    metadata:
      labels:
        app: {{.Values.name}}
    spec:
      containers:
      - name: {{.Values.name}}
        image: {{.Values.image}}
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 500m
            memory: 50Mi
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        resources:
          limits:
            memory: 50Mi
            cpu: 10m
          requests:
            memory: 50Mi
            cpu: 10m
        envFrom:
        - configMapRef:
            name: {{.Values.name}}
